[package]
name = "hasher_wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
sha1 = "0.10.6"
sha2 = "0.10.9"
md5 = "0.8.0"
blake2 = "0.10.6"
whirlpool = "0.10.4"
tiger = "0.2.1"
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib", "rlib"]